arch:
  - arm64

addons:
  hosts:
    - node1

script:
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install ragel
  - sudo apt-get install libpcre3-dev
  
  - rm -rf build
  - mkdir build
  - cd build
  - cmake .. 
  - make -j16