os:
  - linux

arch:
  - x86

addons:
  apt:
    update: true
  hosts:
    - node2

language: 
  - c++
  
script:  
  - cd ..
  - sudo apt-get install libboost-dev

  - wget http://www.colm.net/files/ragel/ragel-6.10.tar.gz
  - tar -zxf ragel-6.10.tar.gz
  - cd ./ragel-6.10
  - sudo ./configure
  - sudo make -j32
  - sudo make install
  
  - cd ./../hyperscan
  - rm -rf build
  - mkdir build
  - cd build
  - cmake .. 
  - make -j32
  - sudo ./bin/unit-hyperscan