arch:
  - arm64

addons:
  hosts:
    - node1

script:
  - sudo apt-get install  libboost-atomic1.58-dev
  - sudo apt-get install ragel
  
  - sudo mkdir pcre_install
  - sudo cd pcre_install
  - sudo wget https://sourceforge.net/projects/pcre/files/pcre/8.43/pcre-8.43.tar.gz
  - sudo tar -zxf pcre-8.43.tar.gz
  - sudo cp -rf ./pcre-8.43 ../pcre
  
  - rm -rf build
  - mkdir build
  - cd build
  - cmake .. 
  - make -j16