os:
  - centos
  - linux

arch:
  - arm64

addons:
  hosts:
    - node1

language: 
  - c
  - C++
  
script:  
  - cd ..
  - sudo apt-get install libboost-dev

  - wget http://www.colm.net/files/ragel/ragel-6.10.tar.gz
  - tar -zxf ragel-6.10.tar.gz
  - cd ./ragel-6.10
  - sudo ./configure
  - sudo make -j16
  - sudo make install
  
  - cd ../
  - wget https://sourceforge.net/projects/pcre/files/pcre/8.43/pcre-8.43.tar.gz
  - tar -zxf pcre-8.43.tar.gz
  - sudo cp -rf ./pcre-8.43 ./hyperscan/pcre
  
  - cd ./hyperscan
  - rm -rf build
  - mkdir build
  - cd build
  - cmake .. 
  - make -j16
  - sudo ./bin/unit-hyperscan
  